INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (1, '659 Bergstrom Falls', 'South Yolanda', 'Papua New Guinea');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (2, '564 Halvorson Square', 'Sheilafurt', 'Congo');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (3, '42251 Huels Corners', 'West Juanashire', 'Uganda');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (4, '74323 Emerald Landing', 'West Lillybury', 'Algeria');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (5, '75415 Metz Path', 'South Winona', 'Romania');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (6, '725 Grady Circles', 'Lake Bridieland', 'Somalia');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (7, '8935 Brayan Rapids', 'Smithamberg', 'Cuba');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (8, '6071 Donnelly Gardens', 'Port Zenastad', 'Rwanda');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (9, '66833 Fadel Course', 'South Jed', 'Denmark');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (10, '66095 Lynch Pine', 'North Minervafort', 'Guam');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (11, '86968 Guido Unions', 'Grimesfurt', 'Egypt');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (12, '8057 Cremin Circle', 'South Jacinto', 'Mali');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (13, '465 Cartwright Canyon', 'Port Kolbyside', 'Slovenia');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (14, '2848 Jarret Stravenue', 'Carletonport', 'Nepal');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (15, '5018 Fay Stream', 'East Angelborough', 'Chad');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (16, '103 Tracy Divide', 'East Eriberto', 'Saint Barthelemy');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (17, '14592 Stehr Street', 'East Janiceborough', 'Mauritius');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (18, '57103 Weimann Row', 'Port Kylaville', 'Guadeloupe');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (19, '34678 Jess Hill', 'Valentinafurt', 'Reunion');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (20, '24168 Ursula Villages', 'Ferrychester', 'Haiti');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (21, '9991 Fay Walk', 'Port Nelson', 'Angola');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (22, '9599 Schiller Dale', 'Bergstromfort', 'Lithuania');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (23, '1542 Schoen Gardens', 'Botsfordview', 'Senegal');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (24, '89589 Jeffry Crossing', 'South Dangelostad', 'Trinidad and Tobago');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (25, '291 Jonathan Village', 'Port Jesusshire', 'Azerbaijan');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (26, '0449 Uriel Isle', 'Wardfort', 'Cook Islands');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (27, '82779 O\'Kon Brook', 'West Anastasia', 'South Georgia and the South Sandwich Islands');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (28, '5974 Chandler Parkway', 'Lakinview', 'Pakistan');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (29, '2449 Cummerata Extensions', 'Port Einartown', 'Tanzania');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (30, '9472 Bessie Island', 'Port Davonte', 'Andorra');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (31, '362 Rolfson Run', 'West Adelia', 'Greece');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (32, '904 Prohaska Points', 'Altenwerthfort', 'Botswana');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (33, '27551 Israel Parkways', 'Beerside', 'Burkina Faso');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (34, '4053 Angeline Burgs', 'Lake Lucienne', 'South Georgia and the South Sandwich Islands');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (35, '25789 King Common', 'Gladycemouth', 'Qatar');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (36, '7984 Madyson Fields', 'New Anselland', 'Kazakhstan');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (37, '67478 Nichole Crescent', 'Britneyborough', 'Aruba');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (38, '8783 Abernathy Plaza', 'Bartonhaven', 'Netherlands Antilles');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (39, '388 Hyatt Overpass', 'Port Nicolettehaven', 'Holy See (Vatican City State)');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (40, '7511 Schroeder Freeway', 'South Janaebury', 'Comoros');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (41, '36749 Carolyne Hollow', 'Ocieland', 'Syrian Arab Republic');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (42, '8298 Marcelino Ways', 'Schuylerberg', 'Belgium');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (43, '1041 Tom Park', 'Bertrandbury', 'France');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (44, '87980 Bryon Station', 'West Eldridgefurt', 'Lebanon');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (45, '9416 Franecki Circle', 'East Valliehaven', 'Jamaica');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (46, '1695 Casper Views', 'Port Jaylenhaven', 'Saint Martin');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (47, '4927 Rosenbaum Glens', 'Douglaschester', 'Lesotho');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (48, '82749 Cummerata Camp', 'Rathside', 'Andorra');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (49, '5146 Mueller Locks', 'Evelynbury', 'Vanuatu');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (50, '2578 Evert Hill', 'New Herthahaven', 'Gibraltar');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (51, '845 Hermiston Hill', 'Wizaland', 'Madagascar');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (52, '276 Williamson Neck', 'Alecberg', 'Netherlands');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (53, '60625 Beulah Terrace', 'Karaton', 'Namibia');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (54, '89875 Ellis Fields', 'New Brendon', 'Niger');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (55, '067 Shields Ports', 'East Jewel', 'Virgin Islands, U.S.');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (56, '12539 Destany Track', 'West Ervin', 'Finland');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (57, '2857 Stella Mall', 'West Marcellushaven', 'Armenia');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (58, '879 Carey Glen', 'South Jonathan', 'Switzerland');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (59, '8545 Willis Points', 'Grantmouth', 'Marshall Islands');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (60, '8582 Jude Highway', 'New Santosport', 'Jersey');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (61, '384 Jaquan Bridge', 'Geraldton', 'Egypt');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (62, '92323 Brielle Trafficway', 'South Burleyfort', 'Virgin Islands, British');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (63, '0272 Eli Stream', 'Trantowtown', 'United States Minor Outlying Islands');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (64, '3595 Heaney Station', 'Mikaylaland', 'Grenada');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (65, '6356 Hermiston Club', 'Lake Fredastad', 'Central African Republic');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (66, '1616 Ebert Station', 'New Marilou', 'Niger');
INSERT INTO DapperBeer.Address (AddressId, Street, City, Country) VALUES (67, '45669 Mary Lodge', 'Abernathyton', 'Zimbabwe');
