INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (1, 'IN DE ZOTTE WILG', 'UITERWG 27 -A', 'AALSMEER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (2, 'BORDEAUX', 'GROTE MARKT 75', 'ALMERE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (3, 'PANNENKOEKENBOOT', 'SLUISKADE 3', 'ALMERE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (4, 'QUERELLE SWING CAFE', 'JULIANASTR 32', 'ALPHEN AD RYN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (5, 'FILMHUIS', 'GROENMARKT 8', 'AMERSFOORT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (6, 'VAN ZANTEN', 'BLOEMENDALSESTR. 2', 'AMERSFOORT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (7, 'AFFOURTIT', 'KONINGINNEWG 209', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (8, 'BLIJBURG AAN ZEE', 'YBURG 99999 -ONG', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (9, 'CASABLANCA', 'ZEEDK 26', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (10, 'CHOC0LATE BAR', '1E VD HELSTSTR 62 -A', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (11, 'DE DAMPKRING', 'HANDBOOGSTR 29', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (12, 'DE DUVEL', '1E VD HELSTSTR 59 -61', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (13, 'DE FONTEYN', 'NIEUWMARKT 13 -15', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (14, 'DE GROENE VLINDER', '1E VD HELSTSTR/A CUYPSTR 130 56', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (15, 'DE SLUYSWACHT', 'JODENBREESTR 1', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (16, 'DE STAALMEESTERS', 'KLOVENIERSBURGWAL 127 -HS', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (17, 'DE TOOG', 'N BEETSSTR 142', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (18, 'DE VERGULDE GAPER', 'PRINSENSTR 30', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (19, 'FESTINA LENTE', 'LOOIERSGR 40 -B', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (20, 'HAARLEMS KOFFIEHUIS', 'PR HENDRIKKD 36', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (21, 'HERENGRACHT', 'HERENGR 435', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (22, 'HERMES', 'ORLYPLN 150', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (23, 'HET BLAAUWHOOFT', 'H JONKERPLN 1', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (24, 'HET PAKHUIS', 'VOETBOOGSTR 10 -12', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (25, 'HILL STREET BLUES', 'WARMOESSTR 52', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (26, 'KATOEN', 'OUDE TURFMARKT 153', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (27, 'KRITERION THEATER', 'ROETERSSTR 170', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (28, 'LUXEMBOURG', 'SPUI 22 -24', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (29, 'MULLIGAN S', 'AMSTEL (HK) 100', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (30, 'O REILLY S', 'PALEISSTR 103 -105', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (31, 'POCO LOCO', 'NIEUWMARKT 24', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (32, 'PUFFELEN', 'PRINSENGR 375 -377', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (33, 'SPANJER & VAN TWIST', 'LELIEGR 60', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (34, 'T MOLENPAD', 'PRINSENGR 653', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (35, 'TABAC', 'BROUWERSGR 101', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (36, 'TER BRUGGE', 'OVERTOOM 578', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (37, 'TETRA', 'NIEUWEZ VOORBURGW 89', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (38, 'THE GETAWAY', 'NIEUWEZ VOORBURGW 250', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (39, 'WESTERGAS TERRAS', 'KLONNEPLN 2', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (40, 'WILDSCHUT', 'R HARTPLN 1 -5', 'AMSTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (41, 'BLUESCAFE', 'NIEUWSTR 74 -A', 'APELDOORN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (42, 'HEEMSKERK', 'MUSSCHENBROEKSTR 25', 'APELDOORN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (43, 'BAR MENEER JANSEN', 'WIJKSTRAAT 47', 'APPINGEDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (44, 'JOEY BAR', 'DIJKSTRAAT 4', 'APPINGEDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (45, 'ALT ARCE', 'RAADHUISPLN 16', 'ARCEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (46, 'JAN VAN HOEK', 'MARKT 12', 'ASTEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (47, 'T SPEKTAKEL', 'PR BERNHARDSTR 44 -46', 'ASTEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (48, 'DE LINDEBOOM', 'STATIONSSTR 9 11', 'BAARLE NASSAU');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (49, 'HERTOG JAN', 'SINGEL 18', 'BAARLE NASSAU');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (50, 'DE KERKBRINK', 'DE BRINK 12', 'BAARN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (51, 'HEEREN VAN BARENDRECHT', 'MIDDENBAAN 99', 'BARENDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (52, 'DE HEBBERD', 'J. V. SCHAFFELAARSTR. 61', 'BARNEVELD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (53, 'DE ROOSBERG', 'BAVELSE HEI 9', 'BAVEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (54, 'TROUBADOUR', 'MARKT 7', 'BEESEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (55, 'FABELS', 'OUDE PRINSWG 9', 'BERGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (56, 'NERO GRANDCAFE RESTAURANT', 'BREELN 5', 'BERGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (57, 'DE TEERKAMER', 'GRT MARKT 13 -14A', 'BERGEN OP ZOOM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (58, 'LIAN BAR', 'HOF 29', 'BERGEYK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (59, 'RIKS CAFE', 'HOF 20', 'BERGEYK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (60, 'DE WITTE ZWAAN', 'HOOGSTR 30', 'BERLICUM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (61, 'FRAPPANT', 'MILROOYSEWG 28', 'BERLICUM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (62, 'D N BEL', 'MARKT 50', 'BLADEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (63, 'IN DE GOUWEGEIT', 'SNIEDERSLN 6', 'BLADEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (64, 'T CARILLON', 'MARKT 2', 'BLADEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (65, 'BAR BECOLOTH', 'ROZEMARYNSTR 2-2A', 'BOXTEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (66, 'BOERKE VERSCHUREN', 'GINNEKENMARKT 13', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (67, 'DE BOSCHWACHTER', 'HUISDREEF 4', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (68, 'DE FRANCISKANER', 'GRT MARKT 31', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (69, 'DE KOGELVANGER', 'GALDERSEWG 55', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (70, 'DE PASTORIE', 'GRT MARKT 48', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (71, 'DE YPELAAR', 'TROMPENBURGSTR 4', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (72, 'DEPENDANCE', 'VISMARKTSTR 2', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (73, 'HOEGAARDEN', 'GRT MARKT 52', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (74, 'INDOOR FUNCENTRE BREDA', 'MYKENBROEK 27', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (75, 'LA RAMBLA', 'GRT MARKT 7', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (76, 'PACKHUYS', 'SPEELHUISLAAN 150', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (77, 'T T HUIS', 'J F KENNEDYLN 15', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (78, 'T TAPPERIJKE', 'GRT MARKT 61', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (79, 'THE PADDOCK', 'GRT MARKT 20', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (80, 'VAN HAM', 'V COOTHPLN 23', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (81, 'YOUNITED BREDA', 'HAMBROEKLN 1', 'BREDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (82, 'IN HOLLAND', 'SCHOOTSENHOEK 23', 'CASTELRE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (83, 'T CHAAMSE WAPEN', 'DORPSSTR 44 -46', 'CHAAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (84, 'DE POORTWACHTER', 'EVERWYNSTR 27 -2A', 'CULEMBORG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (85, 'FRESH FASHION DE VERLEIDING', 'TOLLENSTR 26', 'CULEMBORG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (86, 'APARTHOTEL REKREATIECENTR DELDEN', 'SPORTLN 7', 'DELDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (87, 'DE ENGEL', 'MARKT 66 -A-B', 'DELFT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (88, 'DE RUIF', 'KERKSTR 23', 'DELFT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (89, 'BOEGSCHROEF', 'HANDELSKADE 12', 'DELFZIJL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (90, 'DU BASTION', 'WATERSTRAAT 78', 'DELFZIJL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (91, 'EEMS HOTEL', 'ZEEBADWEG 2', 'DELFZIJL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (92, 'T LOKAAL', 'SCHOOLSTRAAT 27', 'DELFZIJL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (93, 'PANNEKOECKERSHUYS', 'RUITENSPOOR 51', 'DEN HOUT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (94, 'BEEKMAN EN BEEKMAN', 'MARKT 8', 'DEURNE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (95, 'DE BUREN VAN SCHIMMELPENNINCK', 'BRINK 22', 'DEVENTER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (96, 'PASSE PARTOUT', 'BRINK 7 -8', 'DEVENTER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (97, 'TV ZANDLIGT', 'DE BUSKES', 'DIESSEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (98, 'DINGSPILHUUS', 'HOOFDSTRAAT 88', 'DIEVER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (99, 'JANSSEN JANSSEN', 'HG HAM 59', 'DONGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (100, 'BACCHUS', 'BLAUWPOORTSPLEIN 13-14', 'DORDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (101, 'LEKKER BELANGRIJK', 'VOORSTR 256 256A', 'DORDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (102, 'MIRO', 'VOORSTRAAT 256 b', 'DORDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (103, 'SAMSAM', 'VOORSTRAAT 202', 'DORDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (104, 'HOENDERDAAL', 'HOENDERSTEEG 7', 'DRIEBERGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (105, 'BOVEN WATER', 'NW JACHTHAVEN 13', 'DRIMMELEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (106, 'DE KOMBUIS', 'NW JACHTHAVEN 60', 'DRIMMELEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (107, 'DE BENGEL', 'MARKT 13', 'EERSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (108, 'DE MERT', 'MARKT 12', 'EERSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (109, 'DE PIJP', 'NIEUWSTR 2', 'EERSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (110, 'T MASTEBOLLEKE', 'MARKT 14 -16', 'EERSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (111, 'T WAPEN VAN EGMOND', 'VOORSTR 150 -152', 'EGMOND AAN ZEE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (112, 'ALTSTADT', 'STRATUMSEIND 71', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (113, 'BERLAGE', 'KL BERG 16', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (114, 'CASINO', 'AALSTERWG 184', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (115, 'DE BARON', 'KL BERG 26', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (116, 'DE KRAM', 'STRATUMSEIND 42', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (117, 'HOOGSTE TIJD', 'VRYSTR 38', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (118, 'T ROZENKNOPJE', 'HOOGSTR 59', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (119, 'T VONDERKE', 'L NAPOLEONPLN 9', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (120, 'THUNDERROADHOUSE', 'STRATUMSEIND 105', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (121, 'TIPSY DUCK PUB', 'STRATUMSEIND 26', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (122, 'WILHELMINA', 'WILHELMINAPLN 6', 'EINDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (123, 'DE MIDDENSTIP', 'HOOFDSTR 46', 'EPE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (124, 'DE POSTHOORN', 'MARKT 1', 'EPE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (125, 'T TONNETJE', 'W TELLSTR 11', 'EPE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (126, 'IN DEN BOCKENREIJDER', 'DUNSEDK 3', 'ESBEEK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (127, 'BURGEMEESTER', 'MARKT 40', 'ETTEN LEUR');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (128, 'HET WITTE PAARD', 'OUDE BREDASEWG 15', 'ETTEN LEUR');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (129, 'ZUS & ZO', 'RAADHUISPLN 37', 'ETTEN LEUR');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (130, 'HUIS TEN BOS', 'MARKT 43', 'GEERTRUIDENBERG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (131, 'DE CLOWN', 'LANGSTR 99', 'GELDROP');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (132, 'DE KROEG', 'BOGARDEIND 203', 'GELDROP');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (133, 'T WAPEN VAN ZES GEHUCHTEN', 'HG GELDROP 158', 'GELDROP');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (134, 'ALLEMAN', 'VIRMUNDTSTR 47', 'GEMERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (135, 'EETCAFE BULLS', 'DS T.O. HYLKEMAWEG 40', 'GIETHOORN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (136, 'EETCAFE DE SLOOTHAAK', 'BINNENPAD 141', 'GIETHOORN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (137, 'DE TIP', 'BIS. DE VETPLEIN 4', 'GILZE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (138, 'DEN BROOY', 'CHAAMSEWG 21', 'GILZE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (139, 'GILZE', 'L WAGENSTR 30', 'GILZE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (140, 'GRANDCAFE T GELAGH', 'VARKENMARKT 17', 'GORINCHEM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (141, 'GERAATS', 'MARKT 5', 'GRATHEM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (142, 'BUCKSHOT', 'GED ZUIDERDIEP 58 -58A', 'GRONINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (143, 'DE WOLTHOORN', 'TURFTORENSTR 6 -6A', 'GRONINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (144, 'PINTELIER', 'KL KR ELLEBOOG 9', 'GRONINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (145, 'MICHELS', 'HAARENDK 4', 'HAAREN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (146, 'OUT OF THE BLUES', 'KL HOUTSTR 65', 'HAARLEM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (147, 'STUDIO CV', 'GRT MARKT 25', 'HAARLEM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (148, 'T PLEINTJE', 'KERKSTR 51', 'HAPERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (149, 'CAFE DE COMPAGNIE', 'PRINSENGRACHT 29', 'HASSELT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (150, 'LOKAAL', 'A VERHERENTSTR 5', 'HEEMSKERK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (151, 'DE ROOSTER', 'DORPSSTR 33', 'HEERDE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (152, 'PELT', 'PANCRATIUSPLN 48', 'HEERLEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (153, 'T FIELJAAL', 'PANCRATIUSPLN 4', 'HEERLEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (154, 'OUDE HAVEN', 'HAVENKADE 1', 'HENDRIK IDO AMBACHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (155, 'DE BRINK VIJF', 'BRINKSTR 5', 'HENGELO');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (156, 'ST LOUIS', 'EMMAWG 18', 'HENGELO');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (157, 'STRAVINSKY', 'BURG JANSENPLN 20', 'HENGELO');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (158, 'KAFFEE LOMMUS', 'VORSTERMANSPLN 24 -A', 'HEUSDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (159, 'ZWALUWHOEVE', 'ZUIDERZEESTRWG 108', 'HIERDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (160, 'DE ZWAAN', 'VRIJTHOF 17', 'HILVARENBEEK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (161, 'SCHOUWKE', 'VRIJTHOF 18', 'HILVARENBEEK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (162, 'DE BEURS', 'GASTHUISSTR 27', 'HORST');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (163, 'HET CENTRUM', 'WILHELMINAPLN 13', 'HORST');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (164, 'DE ZWIJGER', 'PLEIN 21', 'HOUTEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (165, 'IN DEN BLAUWEN BOCK', 'BADSTR 9', 'KATWYK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (166, 'SCOOBIES', 'VOORSTR 3', 'KATWYK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (167, 'CAFE DE KLOK', 'MOLENSTRAAT 117', 'KINDERDIJK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (168, 'DE KEMPEN', 'HET GROEN 14', 'KNEGSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (169, 'KORENBEURS', 'MARKT 6', 'KRUININGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (170, 'DE DIKKE VAN DALE', 'NIEUWESTAD 69', 'LEEUWARDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (171, 'DE KOPEREN TUIN', 'PRINSENTUIN 1', 'LEEUWARDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (172, 'CAMINO REAL', 'DOELENSTEEG 8', 'LEIDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (173, 'DE BURCHT', 'BURGSTG 14', 'LEIDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (174, 'SSR LEIDEN', 'HOGEWOERD 108', 'LEIDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (175, 'T PRAETHUYS', 'VROUWENKERKK STR 9', 'LEIDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (176, 'DE DIKKE', 'ZWARTEWEG 3', 'LEUSDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (177, 'DE DRIE LINDEN', 'RYT 2', 'LUYKSGESTEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (178, 'CELEBRATION', 'VRYTHOF 11 -11A', 'MAASTRICHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (179, 'D ARTAGNAN', 'GRAANMARKT 3', 'MAASTRICHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (180, 'D INGEL', 'VRYTHOF 13', 'MAASTRICHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (181, 'PERROEN', 'VRYTHOF 35', 'MAASTRICHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (182, 'REKKO', 'VRYTHOF 10', 'MAASTRICHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (183, 'THEATER CLINIQUE', 'PLATIELSTR 9 -A', 'MAASTRICHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (184, 'T HART VAN MADE', 'MARKTSTR 40', 'MADE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (185, 'T TREFPUNT', 'RAADHUISPLN 1 -A', 'MADE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (186, 'CAFE CLOUSO', 'ZUIDEINDE 25', 'MEPPEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (187, 'CAFE DE BOEMEL', 'ZUIDEINDE 27', 'MEPPEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (188, 'HERBERG \'T PLEIN', 'PRINSENGRACHT 1', 'MEPPEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (189, 'UNREAL CAFE', 'P. DE HOOCHSTRAAT 22', 'MEPPEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (190, 'BOMMEL', 'MARKT 85', 'MIDDELBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (191, 'DE GEERE', 'LANGEVIELE 51 -53', 'MIDDELBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (192, 'DE HERBERG', 'POTTENMARKT 2', 'MIDDELBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (193, 'GASTERIJ SMITS', 'HOOFDWEG 170', 'MIDWOLDA');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (194, 'DE ZEEMEEUW', 'ZEEGWEG 1 a', 'MUIDERBERG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (195, 'T TORP VOF', 'DRIESSENSSTRAAT 9-11', 'NEERITTER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (196, 'HET WAPEN VAN NIEUW BEIJERLAND', 'SPUIDK 15', 'NIEUW BEYERLAND');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (197, 'DE BUURVROUW', 'MARKT 6 -7', 'NIEUWEGEIN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (198, 'DE ZWIJGER', 'MARKT 8', 'NIEUWEGEIN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (199, 'JACK S GRILL HOUSE', 'PARKHOUT 2', 'NIEUWEGEIN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (200, 'VAN RIJCKE VORSEL', 'BLAARDORPSEWG 1', 'NIEUWERKERK AD YSSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (201, 'DE ZUIDWAL', 'HULCKESTEYN 2', 'NIJKERK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (202, 'NSVV', 'WILHELMINASTR 2 -BY', 'NUMANSDORP');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (203, 'DE ZAAK', 'STATIONSLN 19', 'NUNSPEET');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (204, 'DE WITTE HOEVE', 'VASSERWG 34', 'NUTTER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (205, 'DORPSZICHT', 'DORPSSTR 10', 'OENE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (206, 'HEUVEL 3', 'HEUVEL 3', 'OOSTERHOUT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (207, 'UILENBOS OGC', 'DUKAATSTR 21', 'OOSTERHOUT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (208, 'OSSENVOORT', 'GROTESTR 30', 'OOTMARSUM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (209, 'DE DORPSHERBERG', 'CASSEWEG 1 a', 'OSPEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (210, 'DE ONTMOETING', 'EIKENBOOMGAARD 8', 'OSS');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (211, 'HEEREN VAN BEIJERLAND', 'MARKTPLN 2', 'OUD BEYERLAND');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (212, 'T OUDE POSTKANTOOR', 'W VOORSTR 23', 'OUD BEYERLAND');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (213, 'THE GAZ STATION', 'RAADHUISPLN 21', 'PANNINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (214, 'TIJDLOOS', 'STELLINGMOLEN 178', 'PAPENDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (215, 'DE STEE', 'HAVERDK 14', 'PRINSENBEEK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (216, 'DE SWAEN', 'MARKT 29', 'PRINSENBEEK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (217, 'KORBELD', 'OUDE LINDERTSEWG 6', 'RAALTE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (218, 'TAVEERNE TIVOLIE', 'ZWOLSESTRAAT 25', 'RAALTE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (219, 'HEEREHUYS', 'HEEREPLN 1', 'RAAMSDONKSVEER');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (220, 'T VEERHUIS', 'MAASDK 33', 'RAVENSTEIN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (221, 'LA GARE', 'WILHELMINALN 46', 'REUSEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (222, 'RUST WAT', 'LINGEDK 16', 'RHENOY');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (223, 'TV RIEL', 'MEYERY 39', 'RIEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (224, 'DE SLEUTEL', 'DORPSSTR 1 -A', 'RIETHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (225, 'THAIPHOON', 'ZWARTBROEKSTR. 31', 'ROERMOND');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (226, 'ZAAL ACHT', 'ZWARTBROEKSTR. 27', 'ROERMOND');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (227, 'DE MORIAAN ETEN EN DRINKEN', 'TONGERLOPLN 9', 'ROOSENDAAL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (228, 'HEKSENKETEL', 'MOLENSTR 60', 'ROOSENDAAL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (229, 'MOEDER OVERSTE', 'MARKT 22', 'ROOSENDAAL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (230, 'DE TUIN', 'PLASZOOM 354', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (231, 'HOV', 'BOSDREEF 120', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (232, 'IJSCLUB KRALINGEN', 'YSCLUBDWARSSTR 1', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (233, 'OP STAANDE VOET', 'STRAATWG 56 -A', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (234, 'SPOT THE LOONY', 'BEYERLANDSELN 33', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (235, 'STALLES', 'NW BINNENWG 11 -A', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (236, 'T BOLWERK', 'GELDERSEKD 1 -A-C', 'ROTTERDAM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (237, 'T BOERKE', 'HOOFDSTR 72', 'RYEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (238, 'OUDE BAREEL', 'BREDASEWG 31', 'RYSBERGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (239, 'BERGER', 'PLEIN 18', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (240, 'FLOOW', 'PLEIN 22', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (241, 'HAAGSCHE KLUISCH', 'PLEIN 20', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (242, 'LAFAYETTE', 'PLEIN 15', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (243, 'LE BYBLOS', 'K POTEN 1', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (244, 'LEOPOLD', 'PLEIN 17', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (245, 'SCHLEMMER', 'L HOUTSTR 17', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (246, 'SILLY S', 'GRT MARKT 25', 'S GRAVENHAGE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (247, 'CORDES', 'PARADE 4', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (248, 'CUBA LIBRE', 'PARADE 5', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (249, 'DE HAVERKIST', 'KORENBRUGSTR 1 -3', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (250, 'DE KEULSE KAR', 'HINTHAMERSTR (HK) 101', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (251, 'DE KEULSE KAR', 'HINTHAMERSTR (HK) 101', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (252, 'HET VEULEN', 'KORENBRUGSTR 9 -A', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (253, 'IN DE KLEINE WERELT', 'MARKT 10 -12', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (254, 'SILVA DUCIS', 'PARADE 6 -7', 'S HERTOGENBOSCH');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (255, 'DE GOUDEN ENGEL', 'MARKT 17', 'SCHAGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (256, 'BESTEK', 'OPWG 2', 'SCHOONHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (257, 'JANSEN EN JANSEN', 'MARKT 23', 'SCHYNDEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (258, 'D N HEMEL', 'MARKT 39', 'SITTARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (259, 'ROUTE 66', 'PAARDESTR 3', 'SITTARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (260, 'HEEREN VAN SLIEDRECHT', 'STATIONSPLEIN 8', 'SLIEDRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (261, 'CENTRAAL', 'WILHELMINAPLN 3', 'SOMEREN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (262, 'T SONNEKE', 'NIEUWSTR 25', 'SON');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (263, 'DE KEYZER', 'VOORSTR 15', 'SPYKENISSE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (264, 'CAFE DE TWEE', 'HOOFDSTRAAT 14', 'STADSKANAAL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (265, 'IN DE WALLEVIS', 'KADE 2', 'STEENBERGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (266, 'T WAPEN VAN STREEFKERK', 'KERKSTR 13', 'STREEFKERK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (267, 'T BAEKSKE', 'MARKTSTRAAT 8-10', 'SWALMEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (268, 'GONZO BAR', 'GROTESTRAAT 77-79', 'TEGELEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (269, 'STACCATO', 'GROTESTRAAT 82', 'TEGELEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (270, 'HARMONIE THORN', 'BOGENSTRAAT 8', 'THORN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (271, 'BOEKANIER', 'STADHUISSTRAAT 11', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (272, 'BOOGIE WONDERLAND', 'PIUSPLN 6 -A', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (273, 'DE PLAATS', 'PIUSPLN 61', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (274, 'DE VOORTUIN', 'TUINSTR 4', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (275, 'DE ZEVEN GEITJES', 'ROESHOFDIJK 18', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (276, 'EXTASE', 'HEUVELRING 112', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (277, 'HET BRUIN KAFEE', 'PIUSPLN 5', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (278, 'HEUVEL 15', 'HEUVEL 15 -A', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (279, 'HOEGAARDEN TILBURG', 'PIUSPLN 2 -2A', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (280, 'KAREL', 'HEUVEL 24', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (281, 'POLLY MAGGOO', 'HEUVEL 10', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (282, 'TRIBUNAAL', 'HEUVEL 14', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (283, 'UIT', 'HEUVEL (HK) 18', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (284, 'VOSSENHOLE', 'REESHOFWEG 55', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (285, 'WAPEN VAN TILBURG', 'SPOORLAAN 362', 'TILBURG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (286, 'CAFE DE KARRE', 'TUKSEWEG 115', 'TUK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (287, 'T CAFEEKE', 'MARKT 2 -4', 'UDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (288, 'T STULPKE', 'MARKT 7', 'UDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (289, 'HEERENPLEIN UTRECHT', 'LUCASBOLWERK 1 -H', 'UTRECHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (290, 'ABSOLUUT', 'MARKT 64', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (291, 'CAFE BASS', 'MARKT 16', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (292, 'CAFE DE SLEUTEL', 'MARKT 20', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (293, 'CAFE DE SWAEN', 'MARKT 29', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (294, 'CAFE SUYKERBUYK', 'LUIKERWEG 145', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (295, 'CAFE ZOMERHOF', 'MAASTRICHTERWEG 265', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (296, 'DE BEL', 'MARKT 24 -26', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (297, 'DE BOUT', 'DORPSTRAAT 39', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (298, 'DE FANTAST', 'F V BESTSTR 9', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (299, 'DE VALK', 'WILHELMINALAAN 48', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (300, 'MILLY\'S', 'MARKT 49', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (301, 'OLD DUTCH', 'MARKT 22', 'VALKENSWAARD');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (302, 'T HART VAN VEGHEL', 'MARKT 31', 'VEGHEL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (303, 'DE LOCHT', 'LOCHT 14', 'VELDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (304, 'SAINT TROPEZ', 'DORPSTR 15', 'VELDHOVEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (305, 'OLD DUTCH', 'MARKT 21', 'VENLO');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (306, 'DE VOSSENBERG', 'ELSPETERBOSWG 1', 'VIERHOUTEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (307, 'THIJSSEN', 'PASTORIESTR 20', 'VLIERDEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (308, 'DE LEUGENAAR', 'BOULEV BANKERT 132', 'VLISSINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (309, 'MONTPERNASSE', 'M DE RUYTERPLN 1', 'VLISSINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (310, 'POPEYE', 'NIEUWENDK 7', 'VLISSINGEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (311, 'DE PINTELIER', 'VALKENBURGERWG 33', 'VOERENDAAL');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (312, 'T PANNELAND', 'VOGELENZANGSED WG 4', 'VOGELENZANG');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (313, 'DE GEREGHTHOF', 'MARKTVELD 8 -10', 'VUGHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (314, 'T GEVELTJE', 'KERKSTR 10', 'VUGHT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (315, 'DE MEESTER', 'GROTESTR 198', 'WAALWYK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (316, 'MARQUIS', 'GROTESTR 246', 'WAALWYK');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (317, 'BOSPOP 2005', 'VRAKKERVELD 2', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (318, 'CAFE BLAAKVEN', 'GEUZENDIJK 35', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (319, 'CAFE DU COMMERCE', 'LANGSTRAAT 65', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (320, 'CAFE GOTCHA', 'BEEKSTRAAT 49', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (321, 'CAFE HARMONIE', 'MUNTPROMENADE 6', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (322, 'CAFE SCHUTTERSHOEVE', 'GROTE STEEG 10', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (323, 'DE BOSUIL', 'VRAKKERVELD 2 c', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (324, 'DE BROUWER', 'OELEMARKT 17-19', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (325, 'HET HOFJE', 'DE OUDE SCHUT 9', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (326, 'LUNCHROOM BEKX', 'MARKT 17', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (327, 'SLIJTERIJ VD FEESTEN', 'HOOGVELDSTRAAT 5', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (328, 'SOC CULTUREEL WERK', 'BOSCHERWEG 57', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (329, 'UT INGELKE', 'KORENMARKT 8', 'WEERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (330, 'T PATERKE', 'KL HEISTR 16', 'WERNHOUT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (331, 'T VEERHUIS', 'POLSTR 1', 'WESSEM');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (332, 'CAFE \'T HOF', 'MARKT 15 a', 'WIJK BIJ DUURSTEDE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (333, 'VINCHOTTE', 'MARKTPLN 1 -G', 'WINSCHOTEN');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (334, 'DONKENHOF', 'ROOSENDAALSESTR 61', 'WOUW');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (335, 'DE BANJAARD', 'NW HAVEN 23', 'ZIERIKZEE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (336, 'DE BEUZE', 'HAVENPLN 7', 'ZIERIKZEE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (337, 'DE GEKROONDE SUIKERBIET', 'NW HAVEN 141', 'ZIERIKZEE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (338, 'DEN BELS', 'MOLENSTR 148', 'ZUNDERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (339, 'DEN HOEK', 'RUCPHENSEWG 14', 'ZUNDERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (340, 'STUYVESANT', 'BREDASEWG 43', 'ZUNDERT');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (341, 'BELGISCHE KEIZER', 'MELKMARKT 58', 'ZWOLLE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (342, 'BIG BULL', 'LUTTEKESTR 33', 'ZWOLLE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (343, 'DE BEURS', 'GRT KERKPLN 2', 'ZWOLLE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (344, 'IRISH INN', 'SASSENSTR (HK) 29', 'ZWOLLE');
INSERT INTO DapperBeer.Cafe (CafeId, Name, Address, City) VALUES (345, 'SWING CAFE DE DOCTER', 'VOORSTRAAT 3-5', 'ZWOLLE');
