INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (678, '(EX-MORREL\'S)', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (679, '3 FLOYDS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (680, '3 FONTEINEN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (681, '3 HORNEN', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (682, 'ABBAYE DE ROCS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (683, 'ABBAZIA ALPIRSBACH', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (684, 'ACHILLES', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (685, 'ADAMBRAU', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (686, 'ADDIS SCOPEL', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (687, 'ADELSKRONEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (688, 'ADNAMS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (689, 'AFFLIGEM', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (690, 'AGROCOOP. PIK-BECEJ', 'YUG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (691, 'ALBANI', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (692, 'ALCATRAZ', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (693, 'ALESMITH', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (694, 'ALLOA', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (695, 'ALPHAND', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (696, 'ALTENMUNSTER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (697, 'AMARCORD - SPRING', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (698, 'AMSTEL', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (699, 'ANCHOR', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (700, 'ANDERSON VALLEY', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (701, 'ANHEUSER - BUSH', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (702, 'ANNOEULLIN', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (703, 'ARCEN', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (704, 'ARCOBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (705, 'ARIZONA ROADHOUSE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (706, 'ARTISANS BRASSEURS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (707, 'ARTOIS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (708, 'ASASHI', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (709, 'ASH VINE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (710, 'ASIA PACIFIC', 'SING');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (711, 'AUCHAN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (712, 'AUGUSTINER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (713, 'AYING', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (714, 'BABB', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (715, 'BADGER', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (716, 'BAJA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (717, 'BALADIN', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (718, 'BALLARD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (719, 'BALLAST POINT', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (720, 'BALTIKA', 'POL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (721, 'BALTUS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (722, 'BANDERSNATCH', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (723, 'BARCHESSA DI VILLA POLA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (724, 'BARNSLEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (725, 'BASS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (726, 'BASS MUSEUM', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (727, 'BATEMANS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (728, 'BAVARIA', 'BRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (729, 'BAVARIA', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (730, 'BAVARIA - ST. PAULI', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (731, 'BAVIK', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (732, 'BEAMISH', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (733, 'BEBA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (734, 'BECKER\'S', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (735, 'BECK\'S', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (736, 'BELHAVEN', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (737, 'BELHAVEN - MONKSCROFT', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (738, 'BELHAVEN - TRAQUAIR HOUSE', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (739, 'BELLEVUE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (740, 'BELL\'S', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (741, 'BENIFONTAINE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (742, 'BERGHOFF', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (743, 'BEXTRIM', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (744, 'BF&D', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (745, 'BI-DU', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (746, 'BIERARIA TSCHLIN', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (747, 'BINDING', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (748, 'BIOS - VAN STEENBERGE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (749, 'BIOS (ABB CORSENDONK)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (750, 'BIRRIFICIO ARTIGIANO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (751, 'BIRRIFICIO DEL BORGO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (752, 'BIRRIFICIO DI COMO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (753, 'BIRRIFICIO ITALIANO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (754, 'BIRRIFICIO LODIGIANO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (755, 'BIRRIFICIO TORINO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (756, 'BIRTANG', 'BIR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (757, 'BLACK MOUNTAIN', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (758, 'BLACK SHEEP', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (759, 'BLUE ANCHOR', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (760, 'BOELENS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (761, 'BOHEMIA', 'MEX');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (762, 'BOON', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (763, 'BOON RAWD', 'THAI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (764, 'BOSTEELS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (765, 'BOSTON BEER CO.', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (766, 'BOSTON BEER CO.                   1', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (767, 'BR. FRANCHES-MONTAGNES', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (768, 'BRAHMA', 'BRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (769, 'BRAIN\'S', 'WAL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (770, 'BRAKSPEAR', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (771, 'BRAND', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (772, 'BRASSERIE D\'AMBLY', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (773, 'BRASSERIE DE TAHITI', 'TAH');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (774, 'BRASSERIES BRUXELLOISES', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (775, 'BRASSERIES SEMEUSE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (776, 'BRAUHAUS FREIBERG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (777, 'BRAUHAUS FREISTADT', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (778, 'BRAUHAUS INGOLSTADT', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (779, 'BRAUHAUS NUSSDORF', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (780, 'BRAUHAUS PFORZHEIM', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (781, 'BRECKENRIDGE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (782, 'BREDA', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (783, 'BRINKHOFF', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (784, 'BRINKUS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (785, 'BRITT', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (786, 'BROOKLYN', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (787, 'BROUGHTON', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (788, 'BRUNEHAUT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (789, 'BUCANERO', 'CUBA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (790, 'BUDVAR', 'CEC');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (791, 'BURGERBRAU BAMBERG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (792, 'BURTON BRIDGE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (793, 'BUSALLA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (794, 'BUTCOMBE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (795, 'C. SCHMIDT', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (796, 'CAFFREY', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (797, 'CALANDA', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (798, 'CALEDONIAN', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (799, 'CALEDONIAN', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (800, 'CALVER', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (801, 'CANARDOU', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (802, 'CANTILLON', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (803, 'CARDINAL', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (804, 'CARLING', 'CAN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (805, 'CARLOW', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (806, 'CARLSBERG', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (807, 'CARLSBERG - PORETTI', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (808, 'CASTELLO DI UDINE', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (809, 'CASTLEMAINE', 'AUS');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (810, 'CELIS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (811, 'CENTRAL DE CERVEJAS', 'POR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (812, 'CENTRALE DELLA BIRRA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (813, 'CERES', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (814, 'CERV. NATIONAL DOMINICANA', 'DOM');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (815, 'CERVECERIA HONDURENA', 'HON');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (816, 'CERVESUR', 'PERU');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (817, 'CERVISIA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (818, 'CEYLON', 'SHK');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (819, 'CHARLES WELLS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (820, 'CIMES', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (821, 'CITTAVECCHIA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (822, 'CNUDDE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (823, 'COBRA', 'INDIA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (824, 'COMMONWEALTH NY', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (825, 'COMPAGNIE DES 3 EPIS', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (826, 'CONISTON', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (827, 'COOP', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (828, 'COREFF', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (829, 'CORNISH', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (830, 'CORONADO', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (831, 'COTLEIGH', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (832, 'COURAGE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (833, 'CREST', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (834, 'CROMBE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (835, 'DALESIDE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (836, 'DAMM', 'SPA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (837, 'DE BIE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (838, 'DE BLOCK', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (839, 'DE CAM', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (840, 'DE DOLLE BROUWERS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (841, 'DE GOUDEN BOOM', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (842, 'DE HOPDUVEL', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (843, 'DE KEERSMAEKER', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (844, 'DE KIKVORSCH', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (845, 'DE KLUIS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (846, 'DE KONINK', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (847, 'DE NEVE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (848, 'DE PROEF', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (849, 'DE RANKE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (850, 'DE RIDDER', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (851, 'DE SMEDT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (852, 'DE SMEDT - CELIS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (853, 'DE SMEDT (ABB AFFLIGEM)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (854, 'DE SMEDT (ABB D\'AULNE)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (855, 'DE SMEDT (ABB DE BROGNE)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (856, 'DE SNOECK - STRUBBE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (857, 'DE TROCH', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (858, 'DEININGER KRONENBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (859, 'DESCHUTES', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (860, 'DEVENISH', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (861, 'DEVENISH                          1', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (862, 'DIEBELS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (863, 'DINCKEL ACKER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (864, 'DINKELACKER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (865, 'DOGFISH HEAD', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (866, 'DOGFISH HEAD                      1', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (867, 'DOOL', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (868, 'DOPPO', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (869, 'DORTMUNDER ACTIEN BRAUREI', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (870, 'DORTMUNDER KRONEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (871, 'DORTMUNDER UNION BRAUREI', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (872, 'DREHER', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (873, 'DRYBOROUGH', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (874, 'DU BOCQ', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (875, 'DU BOCQ (ABB CORSENDONK)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (876, 'DUBLIN', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (877, 'DUBUISSON', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (878, 'DUPONT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (879, 'DUYCK', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (880, 'ECAUSSINNES', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (881, 'EDER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (882, 'EDWIN CHESIRE', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (883, 'EGGENBERGER', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (884, 'EGGENBERGER', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (885, 'EGIS', 'ISL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (886, 'EICHBAUM', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (887, 'EICHOF', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (888, 'EINBECKER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (889, 'ELGOODS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (890, 'ELLEZELLOISE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (891, 'ELRIDGE POPE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (892, 'ENFANTS DE GAYANT', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (893, 'ENGEL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (894, 'ERDINGER WEISSBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (895, 'ERSTE KULMBACHER ACTIENB.', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (896, 'ESPECIALIDADES CERVECERAS', 'MEX');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (897, 'EULER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (898, 'EVANS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (899, 'EVERARDS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (900, 'EXMOOR', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (901, 'EX-WITHBREAD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (902, 'EYLENBOSCH', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (903, 'FALKEN', 'SWE');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (904, 'FANTOME', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (905, 'FARSONS', 'MALTA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (906, 'FAXE', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (907, 'FELDSCHLOSSCHEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (908, 'FIRKIN', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (909, 'FIRKIN', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (910, 'FISCHER - ADELSHOFFEN', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (911, 'FLAGSHIP', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (912, 'FLORISGAARDEN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (913, 'FLYING DOG', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (914, 'FLYING FISH', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (915, 'FOHRENBURGER', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (916, 'FORST', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (917, 'FOSTER\'S - COURAGE', 'AUS');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (918, 'FOUR PEAKS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (919, 'FRANKEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (920, 'FREEDOM', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (921, 'FREEMINER', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (922, 'FRIART', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (923, 'FRUH\'S', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (924, 'FULLER\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (925, 'FURSTENBERG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (926, 'GAFFEL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (927, 'GALE\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (928, 'GAMBRINUS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (929, 'GARDE', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (930, 'GATZWEILER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (931, 'GBP', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (932, 'GEARY', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (933, 'GENERAL LAFAYETTE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (934, 'GIBBS MEW', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (935, 'GIRARDIN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (936, 'GOOSE ISLAND', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (937, 'GORDON BIERSCH', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (938, 'GRADO PLATO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (939, 'GRAND UNION', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (940, 'GRANDE BRASSERIE MODERNE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (941, 'GRANDS COLS', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (942, 'GREENALL WHITLEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (943, 'GREENE KING', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (944, 'GRIESKIRCHNER', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (945, 'GROLSCH', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (946, 'GUINNESS', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (947, 'GUINNESS- SAPPORO', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (948, 'GULPEN - ZWARTE RUITER', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (949, 'GULPENER', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (950, 'H. WEST', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (951, 'HAACHT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (952, 'HAARLEMS', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (953, 'HABERECKL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (954, 'HACKER-PSCHORR', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (955, 'HALL & WOODHOUSE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (956, 'HAMPSHIRE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (957, 'HANNEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (958, 'HANS HOPF', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (959, 'HANSA', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (960, 'HANSA', 'NOR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (961, 'HANSSENS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (962, 'HARBOE', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (963, 'HART', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (964, 'HARVEYS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (965, 'HARVIESTOUN', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (966, 'HASEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (967, 'HEARTLAND', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (968, 'HEATHER ALE', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (969, 'HEIDELBERGER SCHLOSSQUELL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (970, 'HEINEKEN', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (971, 'HEINEKEN', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (972, 'HELLER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (973, 'HENNINGER - SIB', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (974, 'HERBERT WERNER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (975, 'HERFORDER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (976, 'HERREHHAUSER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (977, 'HERRNBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (978, 'HET ANKER', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (979, 'HGI', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (980, 'HIGHGATE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (981, 'HIJOS DE RIVERA', 'SPA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (982, 'HILDEN', 'NIRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (983, 'HIRTER', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (984, 'HOFBRAUHAUS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (985, 'HOFBRAUHAUS FREISING', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (986, 'HOFMARK', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (987, 'HOFSTETTEN', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (988, 'HOLSTEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (989, 'HOOK NORTON', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (990, 'HOP BACK', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (991, 'HOSL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (992, 'HOUGARDEN ARTOIS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (993, 'HURLIMANN', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (994, 'HUYGHE - ARTEVELDE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (995, 'I.N.P.', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (996, 'ICHNUSA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (997, 'IJ', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (998, 'IND COOPE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (999, 'INVERALMOND', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1000, 'IRLBACHER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1001, 'JAHNS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1002, 'JEANNE D\'ARC', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1003, 'JEANNE D\'ARC                      1', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1004, 'JOHN MARTIN', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1005, 'JOHN MARTIN', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1006, 'JOHN SMITH\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1007, 'JOSEPH SIGL', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1008, 'JUPILER', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1009, 'KADEWE', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1010, 'KAISERBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1011, 'KAISERDOM', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1012, 'KALTENBERG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1013, 'KALTENHAUSEN', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1014, 'KANTERBRAU', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1015, 'KARLSBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1016, 'KENYA', 'KEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1017, 'KINDL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1018, 'KING & BARNES', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1019, 'KIRIN', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1020, 'KITZMANN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1021, 'KLOSTERBRAUEREI ANDECHS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1022, 'KNEITING', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1023, 'KOEPFF - ABB. WEINGARTEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1024, 'KOMPANIA PIWOWARSKA', 'POL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1025, 'KONA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1026, 'KONIG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1027, 'KRONENBOURG', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1028, 'KULMBACHER SCHWEIZERHOF', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1029, 'KUNSTHUIS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1030, 'KUPPERS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1031, 'KUR', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1032, 'KYOTO', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1033, 'LA BINCHOISE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1034, 'LA CHOUFFE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1035, 'LA CHOULETTE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1036, 'LA CORNUE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1037, 'LA FABBRICA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1038, 'LA JOLLA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1039, 'LA TRAPPE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1040, 'LA ZARAGOZANA', 'SPA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1041, 'LABATT - MORETTI', 'CAN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1042, 'LAGUNITAS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1043, 'LAMBRATE', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1044, 'LANCELOT', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1045, 'LAPIN KULTA', 'FIN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1046, 'LASKO', 'SLO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1047, 'LAUVAUX', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1048, 'LEES', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1049, 'LEFEBVRE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1050, 'LEFEBVRE (ABB BONNE ESP.)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1051, 'LEFEBVRE (ABB FLOREFFE)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1052, 'LEFT COAST', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1053, 'LEFT HAND', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1054, 'LIDL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1055, 'LIEFMANS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1056, 'LINDEMANS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1057, 'LINDEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1058, 'LOCHER', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1059, 'LOCKWOODS', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1060, 'LOSCHER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1061, 'LOUWAEGE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1062, 'LOWENBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1063, 'M. BROWN', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1064, 'M.S. GUIBERT - INTERBREW', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1065, 'MACLAY', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1066, 'MAES', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1067, 'MAGIC HAT', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1068, 'MAGNOLIA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1069, 'MAHRS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1070, 'MAISEL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1071, 'MALZMUHLE', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1072, 'MANNSFIELD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1073, 'MARQUIS DE BOSH', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1074, 'MARSTON\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1075, 'MARTENS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1076, 'MATT', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1077, 'MATTHEW BROWN', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1078, 'MAXIMILIAAN', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1079, 'MC GUIRE\'S', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1080, 'MC MULLEN', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1081, 'MENABREA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1082, 'MENDOCINO', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1083, 'METEOR', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1084, 'MIBRANA', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1085, 'MILLER', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1086, 'MOCTEZUMA', 'MEX');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1087, 'MODELO', 'MEX');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1088, 'MONT BLANC', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1089, 'MONTEGIOCO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1090, 'MOORTGAT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1091, 'MOORTGAT (ABB MAREDSOUS)', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1092, 'MORDUE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1093, 'MORETTI', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1094, 'MORLAND', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1095, 'MOULIN DES MOINES', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1096, 'MOUSTIER-ST-MARIE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1097, 'MURPHY - DREHER', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1098, 'MUTZIG', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1099, 'N.V. DECA', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1100, 'NEPTUN', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1101, 'NEPTUNE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1102, 'NETHERGATE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1103, 'NEW BELGIUM', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1104, 'NEW GLARUS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1105, 'NIAGARA FALLS', 'CAN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1106, 'NORTH COAST', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1107, 'O\' HANLONS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1108, 'OAKHAM', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1109, 'OFFICINA DELLA BIRRA - BOGGIO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1110, 'OFFICINA DELLA BIRRA - BOGGIO', 'SUI');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1111, 'OFFICINA DELLA BIRRA - BRESSO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1112, 'OLD COLUMBIA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1113, 'OLD WEST', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1114, 'OLPP', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1115, 'OLYMPIA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1116, 'OMMEGANG', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1117, 'ORANGE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1118, 'ORANJEBOOM', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1119, 'ORKNEY', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1120, 'OSTERR. BRAU AG', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1121, 'OTTAKRINGER', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1122, 'OTTER CREEK', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1123, 'OTTER CREEK', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1124, 'OUD BEERSEL', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1125, 'PABST', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1126, 'PAELEMAN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1127, 'PAFFGEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1128, 'PAINE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1129, 'PALM', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1130, 'PALMBRAU ZORN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1131, 'PAPER CITY', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1132, 'PATRIZIER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1133, 'PAULANER THOMASBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1134, 'PELFORTH', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1135, 'PELICAN', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1136, 'PEOPLE\'S PINT', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1137, 'PEOPLE\'S PINT', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1138, 'PERNSTEJN', 'CEC');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1139, 'PERONI', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1140, 'PETE\'S', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1141, 'PIETRA', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1142, 'PINKUS MULLER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1143, 'PITFIELD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1144, 'PIVA ISOKOVA - NIKSIC', 'YUG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1145, 'PIVARA APATIN', 'YUG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1146, 'PLZN (PILSEN)', 'CEC');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1147, 'POLSTER - MENABREA', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1148, 'PORETTI', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1149, 'PORTERHOUSE', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1150, 'PORTLAND', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1151, 'POSTHORN', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1152, 'PRINZ', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1153, 'PUNTIGAM', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1154, 'PUSTERTALER', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1155, 'PYRAMID', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1156, 'RADERMACHER', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1157, 'RAUCHENFELS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1158, 'RCH', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1159, 'REDHOOK', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1160, 'REGENTEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1161, 'REICHELBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1162, 'RIDLEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1163, 'RIEDENBURGER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1164, 'RIEGELE', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1165, 'RINGNES', 'NOR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1166, 'RINGWOOD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1167, 'RITTER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1168, 'RIVA', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1169, 'ROBINSON\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1170, 'ROCHEFORTOISE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1171, 'ROCK BOTTOM', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1172, 'RODENBACH', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1173, 'ROGUE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1174, 'ROHRLBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1175, 'ROMAN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1176, 'ROOSTER', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1177, 'ROSEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1178, 'ROSENBRAUREI', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1179, 'ROTHAUS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1180, 'ROUTE 66', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1181, 'RUDDLE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1182, 'RULLES', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1183, 'S. BERNARDUS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1184, 'S. LEONARD', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1185, 'S. MICHAEL', 'NOR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1186, 'S. MIGUEL ESPANA', 'FIL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1187, 'S. SYLVESTRE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1188, 'SAARFURST', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1189, 'SAILERBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1190, 'SAINT OMER', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1191, 'SAMUEL SMITH', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1192, 'SANDLER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1193, 'SANE', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1194, 'SAPPORO', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1195, 'SARAH HUGHES', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1196, 'SBA', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1197, 'SCARAMPOLA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1198, 'SCHAFF', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1199, 'SCHAFLY', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1200, 'SCHARTNER', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1201, 'SCHELDEBROUWERIJ', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1202, 'SCHLOSS KALTENBERG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1203, 'SCHLOSS STARKENBERG', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1204, 'SCHLOSSB. SOLDENAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1205, 'SCHNEIDER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1206, 'SCHWABEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1207, 'SCOTTISH & NEWCASTLE', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1208, 'SCOTTISH & NEWCASTLE', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1209, 'SEVRES', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1210, 'SHANGAI BREWERIES', 'CINA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1211, 'SHARP', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1212, 'SHEPHERD NEAME', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1213, 'SHERDEL HOF', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1214, 'SHOFFERHOFER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1215, 'SIERRA NEVADA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1216, 'SILENRIEUX', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1217, 'SILLY', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1218, 'SIMMERBERG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1219, 'SINEBRYCHOFF', 'FIN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1220, 'SION', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1221, 'SKINNERS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1222, 'SKOL', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1223, 'SLAGHMUYLDER', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1224, 'SMILE\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1225, 'SMITHWICK\'S', 'IRL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1226, 'SOLANA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1227, 'SONORA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1228, 'SORA\' LAMA\'', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1229, 'SPATEN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1230, 'SPENDRUPS', 'SWE');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1231, 'SQUATTERS', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1232, 'ST. AMAND', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1233, 'ST. AUSTELL', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1234, 'ST. CHRISTOFFEL', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1235, 'ST. JOHANNES BRAU', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1236, 'ST. JOZEF', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1237, 'ST. MONON', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1238, 'ST. PETER\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1239, 'STANGLBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1240, 'STARBESS - ROME', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1241, 'STARBESS - ROME                   1', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1242, 'STAROBNO', 'CEC');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1243, 'STAROPRAMEN', 'CEC');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1244, 'STAUDER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1245, 'STEELHEAD', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1246, 'STEIRERBRAU', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1247, 'STELVIO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1248, 'STERKENS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1249, 'STIEGL', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1250, 'STIFTSBRAUEREI SCHLAGL', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1251, 'STONE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1252, 'STONES', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1253, 'STRAFFE HENDRIJK', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1254, 'STRANGEWAYS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1255, 'STROH', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1256, 'SWIJNKELS', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1257, 'TEIGNWORTHY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1258, 'TEMPO', '  ISR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1259, 'TENNENT\'S CALEDONIAN', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1260, 'TETLEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1261, 'THE COOPER\'S  YARD PUB', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1262, 'THE FROG & ROSBIF PUB', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1263, 'THE ROSE STREET BREWERY', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1264, 'THEAKSTON', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1265, 'THERESIANER', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1266, 'THIRSTY BEAR', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1267, 'THURN UND TAXIS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1268, 'TIMMERMANS', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1269, 'TIMOTHY TAYLOR', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1270, 'TINIMA CAMAGUEY', 'CUBA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1271, 'TITANIC', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1272, 'TOMLINSONS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1273, 'TORRECHIARA', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1274, 'TRAPPIST ABB. ACHEL', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1275, 'TRAPPIST ABB. DE SCOURMONT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1276, 'TRAPPIST ABB. KOENIGHOEVE', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1277, 'TRAPPIST ABB. KOENIGHOEVEN', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1278, 'TRAPPIST ABB. ORVAL', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1279, 'TRAPPIST ABB. ROCHEFORT', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1280, 'TRAPPIST ABB. WESTMALLE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1281, 'TRAPPIST ABB. WESTVLETEREN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1282, 'TRAQUAIR HOUSE', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1283, 'TRENT - S.GEMINIANO', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1284, 'TRIBBIERA', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1285, 'TRIFTERN BAUER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1286, 'TRIPLE F', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1287, 'TROLL', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1288, 'TRUMAN\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1289, 'TSINGTAO', ' CINA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1290, 'TUBORG', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1291, 'TUBORG - PORETTI', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1292, 'TUCHER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1293, 'UERIGE', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1294, 'UNERTL', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1295, 'UNIBROUE', 'CAN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1296, 'UNIBROUE', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1297, 'UNICER', 'POR');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1298, 'UNION', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1299, 'UNION', 'SLO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1300, 'UNION DE BRASSERIES', 'FRA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1301, 'UNITED BREWERIES', 'INDIA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1302, 'UNSER BURGERBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1303, 'UPTOWN SCOTTSDALE', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1304, 'URBAN', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1305, 'USHERS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1306, 'UTRECHTSE', 'NED');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1307, 'VAL DE SAMBRE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1308, 'VAL-DIEU', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1309, 'VALHALLA', 'SCO');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1310, 'VALLEY BEER', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1311, 'VAN DE BOSSCHE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1312, 'VAN DER LINDEN', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1313, 'VAN EECKE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1314, 'VAN HONSEBROUCK', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1315, 'VAN STEENBERGE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1316, 'VAPEUR', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1317, 'VECCHIO BIRRAIO', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1318, 'VECCHIO CALABRESE', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1319, 'VELTINS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1320, 'VER. KARTNER VILLACH', 'AUT');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1321, 'VERHAEGHE', 'BEL');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1322, 'VES GLT COMBINAT', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1323, 'VICTORY', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1324, 'WADWORTH', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1325, 'WARSTEINER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1326, 'WATNEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1327, 'WEBSTER', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1328, 'WEIHENSTEPHAN', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1329, 'WELTENBURG', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1330, 'WELTON DORKINGS', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1331, 'WEYERBACHER', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1332, 'WHITBREAD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1333, 'WIBROE', 'DEN');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1334, 'WIENINGER', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1335, 'WJ KING', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1336, 'WOLF', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1337, 'WOLTERS', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1338, 'WOLVERHAMPTON & DUDLEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1339, 'WOODFORDES', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1340, 'WUHRER', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1341, 'WUNSTER', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1342, 'WURZBURGER HOFBRAU', 'GER');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1343, 'WYCHWOOD', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1344, 'WYE VALLEY', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1345, 'XXX', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1346, 'XXX', 'INDIA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1347, 'YACHIYO', 'JAP');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1348, 'YAKIMA', 'USA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1349, 'YOUNG\'S', 'ENG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1350, 'ZAGREBACKE', 'YUG');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1351, 'ZAHRE SAURIS', 'ITA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1352, 'ZHEJIANG QIANJIANG', 'CINA');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1353, 'ZHIGULI', 'URSS');
INSERT INTO DapperBeer.Brewer (BrewerId, Name, Country) VALUES (1354, 'ZYVIEC', 'POL');
